
name: Build and deploy (Prod & Dev)

on:
  
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Build with Maven
        run: mvn clean install

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar'

  prod:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job to prd
        uses: actions/download-artifact@v3
        with:
          name: java-app

      - name: Deploy to prod
        id: prod-deploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'CICD-production'
          slot-name: 'Production'
          publish-profile: ${{ secrets.prod }}
          package: '*.jar'

  dev:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Developp'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job to dev
        uses: actions/download-artifact@v3
        with:
          name: java-app

      - name: Deploy to dev
        id: dev-deploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'CICD-developp'
          slot-name: 'Production'
          publish-profile: ${{ secrets.dev }}
          package: '*.jar'
